### ISSUE TITLE
Unable to run tests using Github Actions Runner

### ISSUE THREAD

**Issue by nwilging** [orchestral/testbench#339]
- Testbench Version: v5+ (5, 6 and 7 for laravel versions 7-9)
- Laravel Version: 7+ (7, 8 and 9)
- PHP Version: 7.4+ (7.4, 8.0, and 8.1)
- Database Driver & Version: N/A

### Description:
Running unit tests with Github Actions renders errors for every test, complaining about an un-writable directory:
```
Exception: The /home/runner/work/<repository>/vendor/orchestra/testbench-core/laravel/bootstrap/cache directory must be present and writable.
```

### Steps To Reproduce:
Any PHP version 7.4+ should work, this package is being written for all laravel versions 7+, and therefore supports PHP 7.4, 8.0 and 8.1. Each version of Laravel, PHP and Orchestra is failing with the same issue.

Create a new laravel package using `orchestra/testbench` and setup any test case (can be unit, doesn't need to use a DB). Use the following GH workflow yaml and run it. It will fail.
```
name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["7.4", "8.0", "8.1"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php }}
      - name: Run Tests
        run: vendor/bin/phpunit --no-coverage
```

I found [this issue](https://github.com/orchestral/testbench/issues/113) that I hoped would help solve my problem. It did not, as one cannot change ownership of GH action runner directories.

Not sure why Laravel project tests can run but Orchestra cannot. Please advise.
