### ISSUE TITLE
[Workbench] `testbench.yaml` proposed structure for Workbench Improvements

### ISSUE THREAD

**Issue by crynobone** [orchestral/testbench#373]
```yaml
workbench:
  start: /nova
  user: taylor@laravel.com
  guard: web
  sync:
    - from: ./public/
      to: public/vendor/nova
  build:
    - asset-publish
    - create-sqlite-db
    - migrate:refresh
  assets:
    - nova-assets

purge:
  directories: []
  files: []
```

* `sync` would be useful if we want to listen to asset changes directly during development by creating symlink instead of `vendor:publish`
* `build` would be useful to simplify `composer.json`'s `scripts` section, instead of having to remember multiple commands user would just need to run `workbench:build` or `workbench:watch`
* `assets` list of asset tags to be executed with `vendor:publish` via the new `workbench:build`

#### `workbench:build`

This command would be useful to replace common scripts such as the following:

```json
    "build": [
      "@php vendor/bin/testbench vendor:publish --tag=laravel-assets --ansi --force",
      "@php vendor/bin/testbench workbench:create-sqlite-db",
      "@php vendor/bin/testbench migrate:refresh"
    ],
```

Instead, we can build a set of recipes to be defined under `build` configuration.
